//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int Id { get; set; }
        public int ExtraMark { get; set; }
        public Nullable<int> TestId { get; set; }
    
        public virtual Test Tests { get; set; }
        public virtual EnrollerPersonDocument EnrollerPersonDocument { get; set; }
    }
}
