//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectionRequirement
    {
        public int Id { get; set; }
        public int NNrecord { get; set; }
        public int TestId { get; set; }
        public Nullable<int> MinMark { get; set; }
        public Nullable<bool> IsProfile { get; set; }
        public Nullable<bool> IsContest { get; set; }
    
        public virtual EnrollmentProperty EnrollmentProprty { get; set; }
        public virtual Test Test { get; set; }
    }
}
