//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdBranch
    {
        public EdBranch()
        {
            this.EducationBranch1 = new HashSet<EdBranch>();
            this.InstituteDirections = new HashSet<InstituteDirection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Sh_spec { get; set; }
        public Nullable<int> ik_direction { get; set; }
        public Nullable<int> Ik_vip_dep { get; set; }
        public Nullable<System.DateTime> dDate_spec { get; set; }
        public Nullable<decimal> nN_prikaz { get; set; }
        public Nullable<System.DateTime> spDateExit { get; set; }
        public string Cname_qualif { get; set; }
        public string SpecСategory { get; set; }
        public string QualifShortName { get; set; }
        public Nullable<int> ik_FB { get; set; }
        public Nullable<int> ik_main_spec { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<int> id_type_branch { get; set; }
        public Nullable<int> YearNormObuch { get; set; }
    
        public virtual EdDirection Direction { get; set; }
        public virtual ICollection<EdBranch> EducationBranch1 { get; set; }
        public virtual EdBranch EducationBranch2 { get; set; }
        public virtual ICollection<InstituteDirection> InstituteDirections { get; set; }
    }
}
