//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentDocumentType
    {
        public EnrollmentDocumentType()
        {
            this.EnrollerDocuments = new HashSet<EnrollerPersonDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
        public bool IsIdentity { get; set; }
        public bool IsEducational { get; set; }
        public Nullable<int> ik_FB { get; set; }
        public Nullable<int> ik_subFB { get; set; }
        public Nullable<int> ik_type_grazd { get; set; }
    
        public virtual ICollection<EnrollerPersonDocument> EnrollerDocuments { get; set; }
    }
}
