//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public Enrollment()
        {
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int Id { get; set; }
        public int RegNomer { get; set; }
        public decimal nCode { get; set; }
        public int NNrecord { get; set; }
        public Nullable<int> ik_zach { get; set; }
        public int ik_kat_zach { get; set; }
        public System.DateTime dd_pod_zayav { get; set; }
        public Nullable<System.DateTime> dd_vozvr_zayav { get; set; }
        public bool Realy_postup { get; set; }
        public bool IsMain { get; set; }
        public Nullable<System.DateTime> dd_vvoda_zayav { get; set; }
        public Nullable<System.DateTime> dd_online { get; set; }
        public Nullable<double> SchoolAverMark { get; set; }
    
        public virtual EnrollmentProperty EnrollmentProperty { get; set; }
        public virtual EnrollmentState EnrollmentState { get; set; }
        public virtual EnrollmentCategory EnrollmentCategory { get; set; }
        public virtual Enroller Enroller { get; set; }
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
