//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroller
    {
        public Enroller()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public decimal nCode { get; set; }
        public Nullable<decimal> Nn_abit { get; set; }
        public int ik_medal { get; set; }
        public Nullable<int> Ik_vid_pens { get; set; }
        public Nullable<int> Ik_podg { get; set; }
        public Nullable<int> Ik_ob_rab { get; set; }
        public Nullable<int> Ik_special_uchet { get; set; }
        public Nullable<int> Ik_zaved { get; set; }
        public Nullable<decimal> Ngodokon { get; set; }
        public string Cdopsved { get; set; }
        public Nullable<int> ik_pred { get; set; }
        public string cDolgnost { get; set; }
        public Nullable<int> StazYear { get; set; }
        public Nullable<int> StazMonth { get; set; }
        public string cLgot { get; set; }
        public string cOsnovan { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual EnrollerPerson EnrollerPerson { get; set; }
    }
}
