//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollerPerson
    {
        public EnrollerPerson()
        {
            this.EnrollerPersonDocuments = new HashSet<EnrollerPersonDocument>();
        }
    
        public decimal nCode { get; set; }
        public string Clastname { get; set; }
        public string Cfirstname { get; set; }
        public string Cotch { get; set; }
        public Nullable<System.DateTime> Dd_birth { get; set; }
        public string Cplacebirth { get; set; }
        public Nullable<bool> Linval { get; set; }
        public Nullable<bool> Ldeti { get; set; }
        public Nullable<bool> Lrab { get; set; }
        public Nullable<bool> lSex { get; set; }
        public Nullable<bool> Lobchegit { get; set; }
        public string cSotTel { get; set; }
        public string ctelefon { get; set; }
        public string cEmail { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Ik_grazd { get; set; }
        public Nullable<int> Ik_sem_pol { get; set; }
        public string cInn { get; set; }
        public string cStrax { get; set; }
        public Nullable<int> ik_voen_zvanie { get; set; }
        public Nullable<int> itab_n { get; set; }
        public Nullable<int> ik_nac { get; set; }
        public System.Guid PersonGUID { get; set; }
        public string PersonFullName { get; set; }
        public string PersonSmallName { get; set; }
        public string PersName { get; set; }
    
        public virtual ICollection<EnrollerPersonDocument> EnrollerPersonDocuments { get; set; }
        public virtual Enroller Enroller { get; set; }
    }
}
