//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentCategory
    {
        public EnrollmentCategory()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryTypeId { get; set; }
        public Nullable<bool> IsBenefit { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public bool IsRussOlimpWinner { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual CategoryType CategoryType { get; set; }
    }
}
