//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentProperty
    {
        public EnrollmentProperty()
        {
            this.DirectionRequirements = new HashSet<DirectionRequirement>();
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int Id { get; set; }
        public int InstituteDirectionId { get; set; }
        public Nullable<int> BeginDiapazon { get; set; }
        public Nullable<int> EndDiapazon { get; set; }
        public int Year { get; set; }
        public Nullable<int> MestCKP { get; set; }
        public Nullable<int> MestBudjet { get; set; }
        public Nullable<int> MestKontrakt { get; set; }
        public Nullable<int> Ready { get; set; }
        public Nullable<bool> lRussian { get; set; }
        public Nullable<int> MestLgot { get; set; }
    
        public virtual ICollection<DirectionRequirement> DirectionRequirements { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual InstituteDirection InstituteDirection { get; set; }
    }
}
