//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentType
    {
        public EnrollmentType()
        {
            this.States = new HashSet<EnrollmentState>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual ICollection<EnrollmentState> States { get; set; }
    }
}
