//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollerPersonDocument
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Issued { get; set; }
        public string Authority { get; set; }
        public int DocumentTypeId { get; set; }
        public string Number { get; set; }
        public string Series { get; set; }
        public decimal nCode { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<bool> IsReal { get; set; }
    
        public virtual Bonus Bonuses { get; set; }
        public virtual EnrollmentDocumentType EnrollmentDocumentType { get; set; }
        public virtual EnrollerPerson EnrollerPerson { get; set; }
    }
}
