//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentState
    {
        public EnrollmentState()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> EnrollmentTypeId { get; set; }
        public Nullable<int> ik_FB { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual EnrollmentType EnrollmentType { get; set; }
    }
}
