//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstituteDirection
    {
        public InstituteDirection()
        {
            this.EnrollmentProperties = new HashSet<EnrollmentProperty>();
        }
    
        public int Id { get; set; }
        public int EducationBrunchId { get; set; }
        public int InstituteId { get; set; }
        public Nullable<int> YearObuch { get; set; }
        public Nullable<int> ik_rule { get; set; }
        public int EducationFormId { get; set; }
        public int ik_kat_zaved { get; set; }
        public Nullable<int> VidGos { get; set; }
        public int MonthObuch { get; set; }
        public Nullable<System.Guid> DepartmentGUID { get; set; }
        public Nullable<bool> is_short { get; set; }
        public Nullable<bool> is_old { get; set; }
        public Nullable<int> ik_room { get; set; }
    
        public virtual ICollection<EnrollmentProperty> EnrollmentProperties { get; set; }
        public virtual EdBranch EducationBranch { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual EdForm EducationForm { get; set; }
    }
}
