//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institute
    {
        public Institute()
        {
            this.Directions = new HashSet<InstituteDirection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> fDateExit { get; set; }
        public Nullable<bool> bit_calc_nagr { get; set; }
        public string ManagerPostName { get; set; }
        public string DiplExcPatternName { get; set; }
        public string DiplVklExcPatternName { get; set; }
        public Nullable<bool> DiplVklDatPadez { get; set; }
        public Nullable<System.Guid> DepartmentGUID { get; set; }
        public string Cname_fac_rod_pad { get; set; }
        public string Dep_Index { get; set; }
        public Nullable<int> ik_type_department { get; set; }
        public string Cname_fac_small { get; set; }
        public Nullable<System.DateTime> DateDiplomDelivery { get; set; }
    
        public virtual ICollection<InstituteDirection> Directions { get; set; }
    }
}
