//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Bonuses = new HashSet<Bonus>();
            this.DirectionRequirements = new HashSet<DirectionRequirement>();
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> ik_FB { get; set; }
    
        public virtual ICollection<Bonus> Bonuses { get; set; }
        public virtual ICollection<DirectionRequirement> DirectionRequirements { get; set; }
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
