//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models.Enrolleeies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UGTUEnrolleeies : DbContext
    {
        public UGTUEnrolleeies()
            : base("name=UGTUEnrolleeies")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonus> Abit_Bonuses { get; set; }
        public virtual DbSet<DirectionRequirement> ABIT_Diapazon_Disc { get; set; }
        public virtual DbSet<EnrollmentProperty> ABIT_Diapazon_spec_fac { get; set; }
        public virtual DbSet<Test> ABIT_Disc { get; set; }
        public virtual DbSet<Enrollment> ABIT_postup { get; set; }
        public virtual DbSet<EnrollmentState> ABIT_sost_zach { get; set; }
        public virtual DbSet<EnrollmentType> ABIT_type_zach { get; set; }
        public virtual DbSet<TestResult> ABIT_Vstup_exam { get; set; }
        public virtual DbSet<EdDirection> Direction { get; set; }
        public virtual DbSet<EnrollerPersonDocument> Doc_stud { get; set; }
        public virtual DbSet<EnrollmentDocumentType> documents { get; set; }
        public virtual DbSet<EdBranch> EducationBranch { get; set; }
        public virtual DbSet<Institute> Fac { get; set; }
        public virtual DbSet<EdForm> Form_ed { get; set; }
        public virtual DbSet<EnrollmentCategory> Kat_zach { get; set; }
        public virtual DbSet<EnrollerPerson> Person { get; set; }
        public virtual DbSet<InstituteDirection> Relation_spec_fac { get; set; }
        public virtual DbSet<Enroller> Student { get; set; }
        public virtual DbSet<CategoryType> TypeKatZach { get; set; }
    }
}
