//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Campus = new HashSet<Campus>();
        }
    
        public int ik_address { get; set; }
        public int Ik_street { get; set; }
        public string BuildingNumber { get; set; }
        public string StructNumber { get; set; }
        public string FlatNumber { get; set; }
        public string fIndex { get; set; }
    
        public virtual ICollection<Campus> Campus { get; set; }
    }
}
