//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Destination
    {
        public int ik_basedest { get; set; }
        public int Ik_destination1 { get; set; }
        public int Ik_destination2 { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Destination Destination1 { get; set; }
    }
}
