//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrunchType
    {
        public BrunchType()
        {
            this.EducationBranch = new HashSet<EducationBranch>();
        }
    
        public int ik_type_branch { get; set; }
        public string cName_type_branch { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual ICollection<EducationBranch> EducationBranch { get; set; }
    }
}
