//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus
    {
        public Campus()
        {
            this.Room = new HashSet<Room>();
        }
    
        public int ik_campus { get; set; }
        public string CName_campus { get; set; }
        public Nullable<int> ik_address { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Room> Room { get; set; }
    }
}
