//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    
    public partial class Contact
    {
        public string cSotTel { get; set; }
        public string ctelefon { get; set; }
        public string cEmail { get; set; }
    }
}
