//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Areas = new HashSet<Area>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsCIS { get; set; }
        public string Citizenship { get; set; }
        public Nullable<int> ik_FB { get; set; }
        public Nullable<int> CitizenshipId { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
    }
}
