//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculaDisciplines
    {
        public CurriculaDisciplines()
        {
            this.Content = new HashSet<Content>();
        }
    
        public int ik_disc { get; set; }
        public int ik_grp_disc { get; set; }
        public int ik_ckl_disc { get; set; }
        public Nullable<int> ik_podckl { get; set; }
        public string CycleName { get; set; }
        public int CurriculaId { get; set; }
        public Nullable<bool> Uchet { get; set; }
        public Nullable<int> iHour_gos { get; set; }
        public int ik_disc_uch_plan { get; set; }
        public Nullable<int> ik_default_kaf { get; set; }
        public Nullable<int> iIndivid { get; set; }
        public Nullable<int> ViborGroup { get; set; }
        public Nullable<int> ik_pdgrp_disc { get; set; }
        public Nullable<int> iK_spclz { get; set; }
        public string CurriculumUrl { get; set; }
        public Nullable<double> WeekCount { get; set; }
        public Nullable<int> WeekCountInt { get; set; }
        public Nullable<int> WeekCountResidue { get; set; }
    
        public virtual ICollection<Content> Content { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Curricula Curricula { get; set; }
        public virtual DisciplineCycle Cycle { get; set; }
        public virtual DisciplineGroup Group { get; set; }
    }
}
