//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculaYear
    {
        public CurriculaYear()
        {
            this.Curriculas = new HashSet<Curricula>();
        }
    
        public int ik_year_uch_pl { get; set; }
        public int year_value { get; set; }
        public Nullable<System.DateTime> DateDiplomDelivery { get; set; }
    
        public virtual ICollection<Curricula> Curriculas { get; set; }
    }
}
