//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curricula
    {
        public Curricula()
        {
            this.Group = new HashSet<Group>();
            this.Uch_pl1 = new HashSet<Curricula>();
        }
    
        public int ik_uch_plan { get; set; }
        public int ik_year_uch_pl { get; set; }
        public int ik_spec { get; set; }
        public Nullable<int> ik_spclz { get; set; }
        public int ik_form_ed { get; set; }
        public Nullable<bool> IsBRSPlan { get; set; }
        public Nullable<int> ik_year_utverzh { get; set; }
        public Nullable<System.DateTime> date_utv { get; set; }
        public string UserName { get; set; }
        public Nullable<int> is_main { get; set; }
        public Nullable<int> id_parent { get; set; }
        public string grup_comment { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<System.DateTime> date_approved { get; set; }
        public Nullable<int> Nprotocol { get; set; }
        public Nullable<int> ik_kaf { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<Curricula> Uch_pl1 { get; set; }
        public virtual Curricula Uch_pl2 { get; set; }
        public virtual EducationBranch EducationBranch { get; set; }
        public virtual EducationBranch EducationBranch1 { get; set; }
    }
}
