//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.ChildDepartment = new HashSet<Department>();
            this.Faculty = new HashSet<Faculty>();
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid UID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Index { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Phone { get; set; }
        public string ManagerShortName { get; set; }
        public string ManagerName { get; set; }
        public Nullable<System.DateTime> DisbandedOn { get; set; }
        public Nullable<System.Guid> ManagerDepartmentUID { get; set; }
        public Nullable<System.DateTime> FormedOn { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        public virtual ICollection<Department> ChildDepartment { get; set; }
        public virtual Department ManagerDepartment { get; set; }
        public virtual ICollection<Faculty> Faculty { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Manager { get; set; }
    }
}
