//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public Destination()
        {
            this.Document = new HashSet<PersonDocument>();
            this.Roles = new HashSet<Roles>();
            this.Grounds = new HashSet<Destination>();
            this.Derived = new HashSet<Destination>();
        }
    
        public int Ik_destination { get; set; }
        public string cNameDestination { get; set; }
        public string cShortNameDestination { get; set; }
        public Nullable<int> ik_typesup { get; set; }
        public Nullable<bool> IsBase { get; set; }
        public string DescriptionDoc { get; set; }
    
        public virtual ICollection<PersonDocument> Document { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
        public virtual TypeSupply TypeSupply { get; set; }
        public virtual ICollection<Destination> Grounds { get; set; }
        public virtual ICollection<Destination> Derived { get; set; }
    }
}
