//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineType
    {
        public DisciplineType()
        {
            this.discpln = new HashSet<Discipline>();
        }
    
        public byte ik_type_disc { get; set; }
        public string cName_type_disc { get; set; }
        public Nullable<bool> bit_calc_as_practice { get; set; }
        public Nullable<int> ik_ed_izm { get; set; }
    
        public virtual ICollection<Discipline> discpln { get; set; }
    }
}
