//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineGroup
    {
        public DisciplineGroup()
        {
            this.sv_disc = new HashSet<CurriculaDisciplines>();
        }
    
        public int IK_grp_disc { get; set; }
        public string Cname_grp_disc { get; set; }
        public string Ccode_grp_disc { get; set; }
        public bool lVibor { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> VidGos { get; set; }
    
        public virtual ICollection<CurriculaDisciplines> sv_disc { get; set; }
    }
}
