//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationBranch
    {
        public EducationBranch()
        {
            this.EducationBranch1 = new HashSet<EducationBranch>();
            this.Grup = new HashSet<Group>();
            this.Relation_spec_fac = new HashSet<FacultyRel>();
            this.Uch_pl = new HashSet<Curricula>();
            this.Uch_pl1 = new HashSet<Curricula>();
        }
    
        public int ik_spec { get; set; }
        public string Cname_spec { get; set; }
        public string Cshort_spec { get; set; }
        public string Sh_spec { get; set; }
        public Nullable<int> ik_direction { get; set; }
        public Nullable<int> Ik_vip_dep { get; set; }
        public Nullable<System.DateTime> dDate_spec { get; set; }
        public Nullable<decimal> nN_prikaz { get; set; }
        public Nullable<System.DateTime> spDateExit { get; set; }
        public string Cname_qualif { get; set; }
        public string SpecСategory { get; set; }
        public string QualifShortName { get; set; }
        public Nullable<int> ik_FB { get; set; }
        public Nullable<int> ik_main_spec { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<int> id_type_branch { get; set; }
    
        public virtual ICollection<EducationBranch> EducationBranch1 { get; set; }
        public virtual EducationBranch EducationBranch2 { get; set; }
        public virtual ICollection<Group> Grup { get; set; }
        public virtual ICollection<FacultyRel> Relation_spec_fac { get; set; }
        public virtual ICollection<Curricula> Uch_pl { get; set; }
        public virtual ICollection<Curricula> Uch_pl1 { get; set; }
    }
}
