//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationBranch
    {
        public EducationBranch()
        {
            this.Children = new HashSet<EducationBranch>();
            this.Groups = new HashSet<Group>();
            this.Faculties = new HashSet<FacultyRel>();
            this.CurriculaProfiles = new HashSet<Curricula>();
            this.CurriculaDirections = new HashSet<Curricula>();
        }
    
        public int ik_spec { get; set; }
        public string Cname_spec { get; set; }
        public string Cshort_spec { get; set; }
        public string Sh_spec { get; set; }
        public Nullable<int> ik_direction { get; set; }
        public Nullable<int> Ik_vip_dep { get; set; }
        public Nullable<System.DateTime> dDate_spec { get; set; }
        public Nullable<decimal> nN_prikaz { get; set; }
        public Nullable<System.DateTime> spDateExit { get; set; }
        public string Cname_qualif { get; set; }
        public string SpecСategory { get; set; }
        public string QualifShortName { get; set; }
        public Nullable<int> ik_FB { get; set; }
        public Nullable<int> ik_main_spec { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<int> id_type_branch { get; set; }
    
        public virtual ICollection<EducationBranch> Children { get; set; }
        public virtual EducationBranch Parent { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<FacultyRel> Faculties { get; set; }
        public virtual ICollection<Curricula> CurriculaProfiles { get; set; }
        public virtual ICollection<Curricula> CurriculaDirections { get; set; }
        public virtual BrunchType Type_branch { get; set; }
    }
}
