//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationForm
    {
        public EducationForm()
        {
            this.Relation_spec_fac = new HashSet<FacultyRel>();
            this.Uch_pl = new HashSet<Curricula>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ik_FB { get; set; }
        public string ApplicationName { get; set; }
    
        public virtual ICollection<FacultyRel> Relation_spec_fac { get; set; }
        public virtual ICollection<Curricula> Uch_pl { get; set; }
    }
}
