//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Manages = new HashSet<Department>();
            this.Grup = new HashSet<Group>();
        }
    
        public string TypeWorkName { get; set; }
        public string Post { get; set; }
        public System.Guid UID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronimic { get; set; }
        public System.Guid DepartmentUID { get; set; }
        public Nullable<System.Guid> PostUID { get; set; }
        public Nullable<System.DateTime> HiredOn { get; set; }
        public Nullable<System.DateTime> FiredOn { get; set; }
        public Nullable<decimal> StaffCount { get; set; }
        public Nullable<decimal> HourCount { get; set; }
        public int Id { get; set; }
        public string Login { get; set; }
        public Nullable<bool> IsTutorial { get; set; }
        public string Degree { get; set; }
        public string itab_n { get; set; }
        public string Rank { get; set; }
        public string DegreeSmallName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> idEmployee { get; set; }
        public string DegreeScienceName { get; set; }
        public Nullable<double> PPSStuff { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Department> Manages { get; set; }
        public virtual ICollection<Group> Grup { get; set; }
    }
}
