//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyRel
    {
        public FacultyRel()
        {
            this.Group = new HashSet<Group>();
        }
    
        public int ID { get; set; }
        public int BranchId { get; set; }
        public int FacultyId { get; set; }
        public Nullable<int> EducationYears { get; set; }
        public Nullable<int> RuleId { get; set; }
        public int EducationFormId { get; set; }
        public int EducationMonthes { get; set; }
        public int CategoryId { get; set; }
        public Nullable<bool> IsDisbanded { get; set; }
        public Nullable<int> ik_room { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
        public virtual EducationBranch EducationBranch { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Room Room { get; set; }
        public virtual EducationForm EducationForm { get; set; }
    }
}
