//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.StudentGroup = new HashSet<StudGrup>();
        }
    
        public int Id { get; set; }
        public int FacultyRelId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CurriculaId { get; set; }
        public Nullable<int> AdmitsOn { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> DisbandedOn { get; set; }
        public Nullable<int> SpecializationId { get; set; }
    
        public virtual ICollection<StudGrup> StudentGroup { get; set; }
        public virtual FacultyRel FacultyRel { get; set; }
        public virtual Curricula Curricula { get; set; }
        public virtual EducationBranch EducationBranch { get; set; }
    }
}
