//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalityType
    {
        public LocalityType()
        {
            this.Localities = new HashSet<Locality>();
        }
    
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Locality> Localities { get; set; }
    }
}
