//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        public Locality()
        {
            this.Street = new HashSet<Street>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SubAreaId { get; set; }
        public string Index { get; set; }
        public Nullable<int> LocalityTypeId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    
        public virtual SubArea SubArea { get; set; }
        public virtual ICollection<Street> Street { get; set; }
        public virtual LocalityType LocalityType { get; set; }
    }
}
