//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    
    public partial class PersonName
    {
        public string Clastname { get; set; }
        public string Cfirstname { get; set; }
        public string Cotch { get; set; }
    }
}
