//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Documents = new HashSet<Document>();
            this.Name = new PersonName();
            this.Contact = new Contact();
        }
    
        public decimal nCode { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<bool> IsInvalid { get; set; }
        public Nullable<bool> HasChildren { get; set; }
        public Nullable<bool> HasJob { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<bool> IsDormitored { get; set; }
        public Nullable<int> Ik_grazd { get; set; }
        public Nullable<int> Ik_sem_pol { get; set; }
        public string INN { get; set; }
        public string SocialNumber { get; set; }
        public Nullable<int> ik_voen_zvanie { get; set; }
        public Nullable<int> itab_n { get; set; }
        public Nullable<int> ik_nac { get; set; }
        public System.Guid PersonGUID { get; set; }
        public string PersonFullName { get; set; }
        public string PersonSmallName { get; set; }
        public string PersName { get; set; }
    
        public PersonName Name { get; set; }
        public Contact Contact { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
