//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public Reason()
        {
            this.FromStudentGroups = new HashSet<StudGrup>();
            this.ToStudentGroups = new HashSet<StudGrup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ReasonTypeId { get; set; }
        public string ShortName { get; set; }
    
        public virtual ReasonType ReasonType { get; set; }
        public virtual ICollection<StudGrup> FromStudentGroups { get; set; }
        public virtual ICollection<StudGrup> ToStudentGroups { get; set; }
    }
}
