//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonType
    {
        public ReasonType()
        {
            this.Reasons = new HashSet<Reason>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsMain { get; set; }
    
        public virtual ICollection<Reason> Reasons { get; set; }
    }
}
