//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public RoomType()
        {
            this.Room = new HashSet<Room>();
        }
    
        public int ik_room_type { get; set; }
        public string cName_room_type { get; set; }
    
        public virtual ICollection<Room> Room { get; set; }
    }
}
