//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Relation_spec_fac = new HashSet<FacultyRel>();
        }
    
        public int ik_room { get; set; }
        public string Cname_room { get; set; }
        public Nullable<int> ik_campus { get; set; }
        public Nullable<byte> iSeatCount { get; set; }
        public Nullable<int> ik_room_type { get; set; }
        public Nullable<System.Guid> FireProtectionBy { get; set; }
        public string Timetable { get; set; }
        public string Phone { get; set; }
    
        public virtual Campus Campus { get; set; }
        public virtual ICollection<FacultyRel> Relation_spec_fac { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
