//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudGrup
    {
        public int Ik_grup { get; set; }
        public int Ik_zach { get; set; }
        public int ik_kat_zach { get; set; }
        public Nullable<int> Ik_prikazZach { get; set; }
        public int ik_pricZach { get; set; }
        public string cObosnZach { get; set; }
        public Nullable<int> Ik_prikazOtch { get; set; }
        public Nullable<int> ik_pricOtch { get; set; }
        public string cObosnOtch { get; set; }
        public int Ik_studGrup { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Zach Zach { get; set; }
        public virtual Reason FromReason { get; set; }
        public virtual Reason ToReason { get; set; }
    }
}
