//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Zach = new HashSet<Zach>();
        }
    
        public decimal nCode { get; set; }
        public Nullable<decimal> Nn_abit { get; set; }
        public int ik_medal { get; set; }
        public Nullable<int> Ik_vid_pens { get; set; }
        public Nullable<int> Ik_podg { get; set; }
        public Nullable<int> Ik_ob_rab { get; set; }
        public Nullable<int> Ik_special_uchet { get; set; }
        public Nullable<int> Ik_zaved { get; set; }
        public Nullable<decimal> CompletedOn { get; set; }
        public string ExtraInformation { get; set; }
        public Nullable<int> ik_pred { get; set; }
        public string JobPosition { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public Nullable<int> ExperienceMonth { get; set; }
        public string Benefits { get; set; }
        public string Basments { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Zach> Zach { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
