//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public decimal nCode { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Patronimic { get; set; }
        public Nullable<int> Course { get; set; }
        public string Group { get; set; }
        public string EducationForm { get; set; }
        public string Category { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Faculty { get; set; }
        public string Speciality { get; set; }
        public string ManagerName { get; set; }
        public Nullable<System.DateTime> DismissedOrder { get; set; }
        public string ZachNumber { get; set; }
        public string IdentitySeria { get; set; }
        public string IdentityNumber { get; set; }
        public int EducationBranchId { get; set; }
        public Nullable<System.Guid> DepartmentUID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
