//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialTypeClass
    {
        public TutorialTypeClass()
        {
            this.vid_zaniat = new HashSet<TutorialClass>();
        }
    
        public int iK_type_vz { get; set; }
        public string Cname_typ_vz { get; set; }
    
        public virtual ICollection<TutorialClass> vid_zaniat { get; set; }
    }
}
