//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialType
    {
        public TutorialType()
        {
            this.vid_zaniat = new HashSet<TutorialClass>();
        }
    
        public int ikTypeZanyat { get; set; }
        public string TypeZanyat1 { get; set; }
        public bool bitExam { get; set; }
        public bool bitOtchetnost { get; set; }
        public bool bitZach { get; set; }
    
        public virtual ICollection<TutorialClass> vid_zaniat { get; set; }
    }
}
