//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialClass
    {
        public TutorialClass()
        {
            this.Content_UchPl = new HashSet<Content>();
        }
    
        public int iK_vid_zanyat { get; set; }
        public int ikTypeZanyat { get; set; }
        public int iK_type_vz { get; set; }
        public string cName_vid_zanyat { get; set; }
        public string cshort_vid_zanyat { get; set; }
        public Nullable<bool> lTema { get; set; }
        public Nullable<bool> bit_priznak_decompose { get; set; }
        public Nullable<bool> bit_nagr { get; set; }
        public Nullable<bool> bit_must_be_in_uch_plan { get; set; }
        public Nullable<int> year_expire { get; set; }
        public string reason_call { get; set; }
    
        public virtual ICollection<Content> Content_UchPl { get; set; }
        public virtual TutorialTypeClass typ_zan { get; set; }
        public virtual TutorialType TypeZanyat { get; set; }
    }
}
