//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddressEntities : DbContext
    {
        public AddressEntities()
            : base("name=AddressEntities")
        {
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Locality> Gorod { get; set; }
        public virtual DbSet<SubArea> Raion { get; set; }
        public virtual DbSet<Area> Region { get; set; }
        public virtual DbSet<Country> Strana { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<LocalityType> type_gorod { get; set; }
    }
}
