//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProgress
    {
        public string Nn_zach { get; set; }
        public string MarkName { get; set; }
        public Nullable<System.DateTime> DatePassed { get; set; }
        public string cName_vid_zanyat { get; set; }
        public string cName_disc { get; set; }
        public byte n_sem { get; set; }
        public Nullable<int> Ik_grup { get; set; }
        public Nullable<System.DateTime> planDate { get; set; }
        public int iK_disc { get; set; }
        public int iK_vid_zanyat { get; set; }
        public bool bitExam { get; set; }
        public bool bitZach { get; set; }
        public bool lVibor { get; set; }
        public Nullable<int> ViborGroup { get; set; }
        public Nullable<int> Cosenca { get; set; }
        public int Ik_zach { get; set; }
    
        public virtual Zach Zach { get; set; }
    }
}
