//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ugtuapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zach
    {
        public Zach()
        {
            this.StudentGroup = new HashSet<StudGrup>();
        }
    
        public int Ik_zach { get; set; }
        public string Number { get; set; }
        public decimal nCode { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<StudGrup> StudentGroup { get; set; }
    }
}
